on: [ workflow_dispatch ]

jobs:
  docker-job:
    container: alpine:latest
    runs-on: ubuntu-latest
    steps:
    - run: |
        whoami
        sudo whoami
        
        touch file.txt
        sudo touch sfile.txt
        
        ls -la
        
        sudo chmod go-r sfile.txt
        
        ls -la
        
        cat sfile.txt
