on: [ workflow_dispatch ]

jobs:
  docker-job:
    container: alpine:latest
    runs-on: ubuntu-latest
    steps:
    - run: |
        whoami
        sudo whoami
  
  non-docker-job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        whoami
        sudo whoami
