on: [ workflow_dispatch ]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $USER
        whoami
        touch file.txt
        sudo touch sfile.txt
        sudo whoami
        ls -la
